### ISSUE TITLE
Why not always hide traceback?

### ISSUE THREAD

**Issue by KangOl** [modustri/pytest-expecter#2]
As `__tracebackhide__` only have an effect when running with pytest, why not hardcoding `__tracebackhide__ = True`. This will be a noop when running tests with another testrunner.
And even if some other testrunner also implements this magic variable check, it's bonus.

I don't see any case where this traceback should be display.

Then, why not do propose theses changes upstream (PR)?

**Comment by jacebrowning** [comment]
I did propose it upstream, but it was rejected in favor of always showing the full traceback.

You can read the discussion here: https://github.com/garybernhardt/expecter/issues/20

**Comment by jacebrowning** [comment]
If you thought it would help, you could comment with your support of this change on the above issue.
